# Log user IP on console when a player join
log_console: false

###########################################
# Security system
# Allow only connection from YOUR proxy (Bungee or Velocity)
#
# Why ? You can connect to spigot's server thanks to custom Bungee server, and be OP.
#
only_proxy:
  enabled: false
  kick: true
  bungee_ip:
  - 1.2.3.4
  #
  # If you want an autoban when wrong Proxy
  # Keep it empty to don't run command
  # Command dispatch from CONSOLE !
  command_wrong_proxy: ""
#
###########################################

###########################################
# Ban a specific IP
# Now, you cannot ban IP list, but it comes soon.
#
banned-ip:
  enabled: false
  disallow:
  - "127.0.0.1"
#
###########################################

###########################################
#
# Manage when player is using VPN, proxy or hosting
# 
#
check-wrong:
  enabled: true
  vpn:
    kick: true
    ban: false
  proxy:
    kick: true
    ban: false

#
###########################################

###########################################
# Notify alert when multiple player connect on the same IP
#
# The action have to be :
# action_type:value
#
# Available actions :
# console : Run command from console
# run : The player wil run the command
# send : Send to player with permission given in "permission" value (or OP if empty/not set).
# kick : Kick the player with the given message
#
# In actions, this is all placeholders :
# %name% : The name of player which just join
# %uuid% : The uuid of player which just join
# %count% : Amount of player on same IP
# %all_names% : All names of player on the same IP (including just join player). Format: "Name1, Name2"
#
ip-notify:
  4:
    # this is used ONLY with "send" action. Other are runned even if the player don't have this permission
    #permission: "ipmanager.notify"
    actions:
    - "kick:Too many account on same IP (%count%/3).\nAccount on IP: %all_names%"
#
###########################################


###########################################
#
# Manage bans
#
ban:
  # Currently, there is only one processor: 'command'
  processor: "command"
  #####
  # Available placeholders:
  # %uuid% : Player UUID
  # %name% : Player name
  # %reason% : Reason of ban
  command: "ban %name% %reason%"
#
###########################################


messages:
  log_console: "%name% (%uuid%) just connect with IP %ip%"
  wrong_proxy: "&cPlease connect via &eplay.myserver.net &c!"
  precise: "&cPrecise the player name or the player UUID"
  reloaded: "&aPlugin IpManager reloaded !"
  cannot_found: "&cCannot found player !"
  not_registered: "&cIP of &e%name% &cnot registered"
  not_allowed: "&cYou are not allowed to use &l%type%&c."
  unknow: "Unknow"
  yes: "Yes"
  no: "No"
  getip:
    # What is the difference between 'ip', 'bungee_ip' and 'fai' ?
    # ip: the real user ip
    # proxy_ip: the IP of the proxy (same as 'ip' if without proxy). Used in "only_proxy" system
    # fai: The FAI ip (can doesn't work, it depend of the location and the fai of the user)
    #
    online: # If the player is online
    # All placeholders available :
    # %city% : The city of the IP
    # %region% : The region of the IP (like 'California')
    # %region_code% : the region code of the IP (like 'CA')
    # %country_code% : The IP's country code (like 'US')
    # %country_name% : The IP's country name (like 'Washington')
    # %continent_code% : The continent code (like 'NA')
    # %in_eu% : If the IP is in EU
    # %timezone% : Timezone of the country of the IP (like 'America/Los_Angeles')
    # %languagues% : Lang of the country (like 'en-US,es-US,haw,fr')
    # %asn% : The number of the organization which is owner of the IP
    # %org% : Organization owner of the IP
    - "&7&m-------&e GetIP of &c%name% &7&m-------"
    - "&aIP: &e%ip% &ain &e%city% &a(&e%country_code%&a)"
    - "&aProxy: &e%proxy_ip%. &aFAI: &e%fai% &aOwned by &e%org%"
    - "&aVPN: &e%vpn%&7, &aProxy: &e%proxy%&7, &aHosting: &e%hosting%&7."
    - "&7&m-------&e GetIP &7&m-------"
    offline: # If the player is offline
    - "&7&m-------&e GetIP &7&m-------"
    - "&aIP of &c%name% &a(&e%uuid%&a)"
    - "&aIP: &e%ip%"
    - "&aProxy: &e%proxy_ip%. &aFAI: &e%fai%"
    - "&aVPN: &e%vpn%&7, &aProxy: &e%proxy%&7, &aHosting: &e%hosting%&7."
    - "&7&m-------&e GetIP &7&m-------"

